name: Setup Fyne for Windows
description: Install required Windows packages for Fyne apps

runs:
  using: composite
  steps:
  - name: Setup MSYS2
    uses: msys2/setup-msys2@v2
    with:
      msystem: mingw64
      update: true
      install: >-
        git mingw-w64-x86_64-toolchain mingw-w64-x86_64-go

  - name: Ensure Go bin path
    shell: bash
    run: |
      echo "export PATH=\$PATH:/mingw64/bin:$(go env GOPATH)/bin" >> ~/.bashrc
