name: Setup Fyne for Linux
description: Install required Linux packages for Fyne apps

runs:
  using: composite
  steps:
    - name: Install Fyne dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc \
          libgl1-mesa-dev \
          xorg-dev \
          libxkbcommon-dev \
          pkg-config
