// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/dark_theme_icon.svg
var resourceDarkthemeiconSvgData []byte
var resourceDarkthemeiconSvg = &fyne.StaticResource{
	StaticName:    "assets/dark_theme_icon.svg",
	StaticContent: resourceDarkthemeiconSvgData,
}

//go:embed assets/light_theme_icon.svg
var resourceLightthemeiconSvgData []byte
var resourceLightthemeiconSvg = &fyne.StaticResource{
	StaticName:    "assets/light_theme_icon.svg",
	StaticContent: resourceLightthemeiconSvgData,
}
